name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
        with:
          deno-version: "v1.x"
      - name: Show Deno version
        run: deno --version
      - name: Run lint
        run: make lint
      - name: Install dem-local
        run: |
          make install-local
          echo $HOME/.deno/bin >> $GITHUB_PATH
      - name: Run tests
        run: |
          make test
