name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.2.0
      - name: Show Deno version
        run: deno --version
      - name: Run tests
        run: make test/cmd
